### ISSUE TITLE
Return model on update

### ISSUE THREAD

**Issue by feluelle** [igorbenav/fastcrud#106]
**Is your feature request related to a problem? Please describe.**

When performing an [update](https://igorbenav.github.io/fastcrud/api/fastcrud/#fastcrud.FastCRUD.update), I am missing the option to retrieve the updated model. I explicitly have to [get](https://igorbenav.github.io/fastcrud/api/fastcrud/#fastcrud.FastCRUD.get) the updated model from the DB.

**Describe the solution you'd like**

I would like to leverage the sqlalchemy Update [returning](https://docs.sqlalchemy.org/en/20/core/dml.html#sqlalchemy.sql.expression.Update.returning) clause which allows returning the data after the update has been performed.

**Comment by JakNowy** [comment]
That's a good point and should be pretty simple to implement. Would you like to work on it maybe?

Let's add optional returning parameter as a list of fields and chain the stmt with .returning if it's present.

**Comment by feluelle** [comment]
Yes, I can give it a try. :)

**Comment by feluelle** [comment]
Unfortunately, that would probably mean we need to remove the `commit` arg and ideally we do the same as we do for `get` and return the data as a model. I would even suggest we split the current function into `update` and `update_multi`.
