### ISSUE TITLE
All endpoints have `local_kw` query parameter when you try example

### ISSUE THREAD

**Issue by YuriiMotov** [igorbenav/fastcrud#12]
**Describe the bug or question**
When you try running code from examples in documentation, all created endpoints have mandatory query parameter `local_kw`.

**To Reproduce**
Just create and run app, using the examples from documentation.

**Description**
The problem is that in the examples `async_session` object is used as a session dependency. The `__call__` method of this object has `**local_kw: Any` as a parameter. And FastAPI treats it as mandatory query parameter for that endpoint.

**Screenshots**
![fastcrud](https://github.com/igorbenav/fastcrud/assets/109919500/d5e401d8-b50b-4fca-a4c1-d89136362b37)

**Additional context**
-

**Comment by igorbenav** [comment]
fixed by #13
