### ISSUE TITLE
disable specific crud methods?

### ISSUE THREAD

**Issue by LeiYangGH** [igorbenav/fastcrud#144]
**Is your feature request related to a problem? Please describe.**
How to disable `create`/`delete`, for example? i don't see it in docs.

**Describe the solution you'd like**
crud_router constructor, set `create_schema=None`, `delete_schema=None`,

but doesn't work. docs still show such methods.

**Comment by igorbenav** [comment]
Do you mean [something like this](https://igorbenav.github.io/fastcrud/advanced/endpoint/#selective-crud-operations)?

**Comment by LeiYangGH** [comment]
yes. thanks, i saw this argument but not aware it was used for specifying subset of crud methods.
i think my problem solved.
