### ISSUE TITLE
He utilizado tu repositorio en mi proyecto

### ISSUE THREAD

**Issue by techotaku1** [igorbenav/fastcrud#156]
**He utilizado tu repositorio en mi proyecto**

Hola,

Quería avisarte que he utilizado tu repositorio [fastcrud](https://github.com/igorbenav/fastcrud) en mi propio proyecto. Me ha sido de gran ayuda y he integrado las funcionalidades en mi aplicación de [FastAPI-CRUD].

Si estás interesado en ver cómo lo he usado, aquí está el enlace a mi repositorio: [Fastapi-CRUD](https://github.com/techotaku1/FASTAPI-CRUD-1).

Gracias por tu trabajo y por compartirlo con la comunidad.

Saludos,
[techotaku1](https://github.com/techotaku1)

**Comment by igorbenav** [comment]
Really nice project! I think I’ll create a showcase page in the docs to add all your projects there!
