### ISSUE TITLE
Update method 'column' variable overwritten 

### ISSUE THREAD

**Issue by theos15** [igorbenav/fastcrud#157]
**Describe the bug or question**
In certain environments the line in the update method:
`model_columns = {column.name for column in inspect(self.model).c}
`writes over the column import for the below line:
`stmt = stmt.returning(*[column(name) for name in return_columns])
`

**Description**
column import being overwritten by local loop, resulting in the following error:

UnboundLocalError: cannot access local variable 'column' where it is not associated with a value

Updating the line with a new variable name fixes the issue:
`model_columns = {_column.name for _column in inspect(self.model).c}
`
**Screenshots**
![image](https://github.com/user-attachments/assets/caef8107-e409-422f-b1d8-a266168959cc)```python

**Comment by renja-g** [comment]
I also just got this error:
```py
updated_post = await crud_profile.update(db=db, object=values, schema_to_select=ProfileRead, return_as_model=True, id=id)
```
```
fastcrud/crud/fast_crud.py", line 1980, in update
    stmt = stmt.returning(*[column(name) for name in return_columns])
                            ^^^^^^
UnboundLocalError: cannot access local variable 'column' where it is not associated with a value
```

**Comment by igorbenav** [comment]
I'll upload a fix. Do you want to do it, @theos15?

**Comment by renja-g** [comment]
> I'll upload a fix. Do you want to do it, @theos15?

I would appreciate that
