### ISSUE TITLE
Is there a way to customise the path suffix added by crud_router ?

### ISSUE THREAD

**Issue by mde-pach** [igorbenav/fastcrud#16]
As you can see on the swagger definition attached to this description, The crud_router create automatically routes with suffix `get`, `create` or `get_multi`...

<img width="1308" alt="Screenshot 2024-02-08 at 12 30 12" src="https://github.com/igorbenav/fastcrud/assets/12986913/a8a0f95d-4f3d-4b5f-8091-105a2edbd987">

I would like to implement a more "clean" and standard way of route suffix creation like
- create => `POST /api/todos/`
- get -> `GET /api/todos/{id}`
- get_multi -> `GET /api/todos/`

etc...

But I don't know if there is a way to specify it easily

Anyway, if it's not the case I think it could be a good feature and I will be happy to help on it

**Comment by mde-pach** [comment]
Yeah for sure, I'm having a look in the next 2 weeks :)

**Comment by igorbenav** [comment]
Hey, @mde-pach, are you still doing it or may I?

**Comment by mde-pach** [comment]
Sorry about that, I had to stop working on my personal project which was using fastcrud because I had too much work in my real job 😂
Glad you manage it on you own 👍

**Comment by igorbenav** [comment]
Hey, @mde-pach, no worries! Thanks for the issue!
