### ISSUE TITLE
FastCRUD seems to only be compatible with fastapi>=0.100.0,<0.112.0, is it intentional?

### ISSUE THREAD

**Issue by Mumbawa** [igorbenav/fastcrud#165]
When installing fastcrud via uv a get the following:
$ uv add fastcrud==0.15.0

  × No solution found when resolving dependencies:
  ╰─▶ Because fastcrud==0.15.0 depends on fastapi>=0.100.0,<0.112.0 and your project depends on fastapi==0.114.0, we can conclude that your project and
      fastcrud==0.15.0 are incompatible.
      And because your project depends on fastcrud==0.15.0, we can conclude that your project's requirements are unsatisfiable.

**Comment by igorbenav** [comment]
My mistake, I'll update it later today

**Comment by Mumbawa** [comment]
Thank you!

**Comment by igorbenav** [comment]
fixed by #166
