### ISSUE TITLE
commit=True have no effect when return_as_model==True

### ISSUE THREAD

**Issue by henriquebonadio** [igorbenav/fastcrud#168]
I am using crud.update with return_as_model=True and schema_to_select=MySchema.
It updates the record, returns the updated result, but never commits the transaction.
I see a rollback log when the task finishes.

```
db-1  | 2024-09-30 20:35:32.270 UTC [143] LOG:  statement: ROLLBACK;
```

It seems like it happens as there are some return lines prior to the comit logic (these returns trigger when return_as_model==True).

https://github.com/igorbenav/fastcrud/blob/10704996044469ebffe64aa4d2e19048cb431a9f/fastcrud/crud/fast_crud.py#L2219:L2241

**Comment by ankur09011** [comment]
+1

**Comment by igorbenav** [comment]
I'll fix this

**Comment by Qwiko** [comment]
+1
