### ISSUE TITLE
upsert_multi doesn't commit

### ISSUE THREAD

**Issue by konradbeck-creditech** [igorbenav/fastcrud#170]
**Describe the bug or question**
My skill is fairly limited, so I might be wrong. But as far as I can tell.

I get an Id back but it's not commit to the db. the normal upsert internally calls the create and update which support commit, but upsert_multi takes a very different route.

**Comment by feluelle** [comment]
Yes, that's intentional, but I can also see the argument of having consistency between `upsert` and `upsert_multi`.

I'll create a PR for that.
