### ISSUE TITLE
Displaying json response schema in swagger UI

### ISSUE THREAD

**Issue by Mumbawa** [igorbenav/fastcrud#183]
Is there a way to get the json response schema in the swagger UI for the get and get multi end points when created with `crud_router()`?

Basically when I create a set of endpoints (Tenants in the image below ) I would like to see the structure of the json in the response, instead of a simple string...

![image](https://github.com/user-attachments/assets/a84625a4-f2cb-438c-9f03-b2e5e49bcc16)

**Comment by igorbenav** [comment]
I'll take a look at this soon
