### ISSUE TITLE
How to perform JOIN across many to many relation?

### ISSUE THREAD

**Issue by JakNowy** [igorbenav/fastcrud#33]
**Describe the bug or question**
I have 2 models, A and B, in M2M relationship linked via an ABAssociation table. The documentation explains a way to perform left and outer joins using JoinConfig. It lacks details on how to proceed with M2M relationships. Is that possible?

**To Reproduce**
Please provide a self-contained, minimal, and reproducible example of your use case
```python
class A(SQLModel, table=True):
    id: int | None = Field(primary_key=True, index=True)

class B(SQLModel, table=True):
    id: int | None = Field(primary_key=True, index=True)

class VideoSearchAssociation(SQLModel, table=True):
    a_id: int | None = Field(primary_key=True, foreign_key="a.id")
    b_id: int | None = Field(primary_key=True, foreign_key="b.id")
```

**Description**

**Screenshots**

**Additional context**

**Comment by igorbenav** [comment]
Hey, @JakNowy, it works if you do this:

```python
join_condition_1 = A.id == ABAssociation.a_id
join_condition_2 = ABAssociation.b_id == B.id

joins_config = [
    JoinConfig(
        model= VideoSearchAssociation,
        join_on=join_condition_1,
        join_type="inner",
        join_prefix="association_"
    ),
    JoinConfig(
        model=B,
        join_on=join_condition_2,
        join_type="inner",
        join_prefix="b_"
    )
]

records = await crud_a.get_multi_joined(
        db=async_session,
        joins_config=joins_config,
)
```

Naturally, It should not work for get_joined, it's a get_multi_joined situation by default. I'll add this in the docs.

**Comment by igorbenav** [comment]
I noticed that the count is wrong in `get_multi_joined` for Many-to-Many relationships (the data is fetched correctly, but the total_count is wrong), but I wrote a fix already. I'm finishing the documentation on Many-to-Many and writing the tests and I'll update it later today.

**Comment by igorbenav** [comment]
Docs added [here](https://igorbenav.github.io/fastcrud/advanced/joins/#complex-joins-using-joinconfig)
