### ISSUE TITLE
Any reason why FastCRUD  depends on FastAPI <0.110.0

### ISSUE THREAD

**Issue by imankulov** [igorbenav/fastcrud#39]
Is there any specific reason why FastCRUD depends on FastAPI <0.11.0 and is it easy to fix? The [FastAPI changelog](https://fastapi.tiangolo.com/release-notes/#01100) doesn't outline any breaking changes except for dependencies with "yield" and "except".

Thanks!

**Comment by igorbenav** [comment]
Not really, 0.109.0 was the latest when i launched fastcrud, so I didn't know if breaking changes would be introduced in 0.110.0. Guess I just forgot to bump the version in the pyproject.toml to be honest.

**Comment by igorbenav** [comment]
Closed by #42
