### ISSUE TITLE
Fix handling dependencies

### ISSUE THREAD

**Issue by igorbenav** [igorbenav/fastcrud#53]
**Describe the bug or question**
In the docs, we have something like

```python
router = crud_router(
    ...
    read_deps=[get_current_user],
    update_deps=[get_current_user],
    ...
)
```

When actually the correct way would be:

```python
from fastapi import Depends

router = crud_router(
    ...
    read_deps=[Depends(get_current_user)],
    update_deps=[Depends(get_current_user)],
    ...
)
```

I'd like some opinion if possible on whether we should fix the docs or change the way it works. The latter is more explicit, but I think the former might be simpler for the end user. 

If the former is used, stuff like getting non-callable objects or dependencies that are already wrapped must be handled.

**Comment by JakNowy** [comment]
Both approaches are acceptable in my opinion, but I would personally prefer the former (without Depends). Let me just define what dependency is required and make the library handle it as it needs. That's also less verbose.

**Comment by JakNowy** [comment]
Also note that in the newest version of [tiangolo fastapi template](https://github.com/tiangolo/full-stack-fastapi-template/blob/master/backend/app/api/routes/users.py) it's not required to wrap the deps in Depends. He leverages [Dependency annotations ](https://github.com/tiangolo/full-stack-fastapi-template/blob/master/backend/app/api/deps.py#L25) instead. Maybe we could support both cases, by conditionally wraping deps when needed?

**Comment by igorbenav** [comment]
I'll change stuff and it should be released over the weekend, there are a few other changes and I need to write the documentation for them as well.

**Comment by igorbenav** [comment]
> Also note that in the newest version of [tiangolo fastapi template](https://github.com/tiangolo/full-stack-fastapi-template/blob/master/backend/app/api/routes/users.py) it's not required to wrap the deps with Depends in route parameters. 

Yeah, this would definitely be a more elegant approach, but it's still more work to the user.

> Maybe we could support both cases, by conditionally wraping deps when needed?

I think we should pick something and stick to it, support it in the best possible way. One flexibility we could allow is:

We get a sequence of functions, each function might have a type hint, if it does, we use the dependency annotation with the custom type, if not, we do it with `Callable`.
