### ISSUE TITLE
SQLModel classes fail type checking with FastCRUD

### ISSUE THREAD

**Issue by slaarti** [igorbenav/fastcrud#58]
**Describe the bug or question**

The `FastCRUD` class expects that the model that's passed to it is a subclass of SQLAlchemy's `DeclarativeBase`. SQLModel, meanwhile, derives a metaclass from SQLAlchemy's `DeclarativeMeta` and uses that as its base. It therefore isn't a subclass of `DeclarativeBase` and passing a class derived from `SQLModel` to `FastCRUD` fails type checking:

```
$ pyright mve.py
.../mve.py
  .../mve.py:12:22 - error: Argument of type "type[Store]" cannot be assigned to parameter "model" of type "type[ModelType@FastCRUD]" in function "__init__"
    Type "Store" is incompatible with type "DeclarativeBase"
      "Store" is incompatible with "DeclarativeBase" (reportArgumentType)
1 error, 0 warnings, 0 informations
```

**To Reproduce**

The MVE used to produce the above error message. The documentation says this should work, and it probably does actually run, but again, it fails type checking (using "standard" `typeCheckingMode`):

```python
from typing import Annotated

from fastcrud import FastCRUD
from sqlmodel import Field, SQLModel


class Store(SQLModel, table=True):
    id: Annotated[str, Field(primary_key=True)]
    name: Annotated[str, Field(unique=True)]


StoreCRUD = FastCRUD(Store)
```

**Comment by igorbenav** [comment]
Thanks, @slaarti, I'm fixing this one ASAP!

**Comment by AndresPrez** [comment]
any news?

**Comment by igorbenav** [comment]
Totally forgot about this (a bunch of new stuff came out), I'll work on it

**Comment by kdcokenny** [comment]
I'll take this up
