### ISSUE TITLE
Streamlined REST API Methods then using the default endpoint generator

### ISSUE THREAD

**Issue by waza-ari** [igorbenav/fastcrud#67]
**Is your feature request related to a problem? Please describe.**
First of all, thanks for your work and sorry for opening a million issues. This one is more of a debate I assume, as there is no "right" way of doing it. I do have the feeling that the current standard set of endpoints I suboptimal. Basically using the example:

```python
router = crud_router(
    session=get_db,
    model=Ability,
    create_schema=AbilityCreateSchema,
    update_schema=AbilityUpdateSchema,
    path="/abilities",
    tags=["abilities"],
)
```

Yields these endpoints:

<img width="542" alt="image" src="https://github.com/igorbenav/fastcrud/assets/4508976/a8cb5c27-d206-47aa-9e65-f9fe9327d163">

One example is: `DELETE /api/v1/abilities/delete/{id}` - we already know its deleting because of the HTTP verb - why does it need to be in the path again? The same applies to `create` (POST), `update` (PATCH) and `get` (GET) as well.

**Describe the solution you'd like**
I'd love to be able to configure something "cleaner" (although I'm fully aware that's very opinionated) like this:

<img width="670" alt="image" src="https://github.com/igorbenav/fastcrud/assets/4508976/2abf9f58-12a9-423f-8ab9-a46461c6ba1f">

The HTTP Verb here together with the endpoint is quite descriptive in itself (and obviously I should change the default endpoint description, but its just for the demo).

Its not possible to achieve this with c[ustomised endpoint names](https://igorbenav.github.io/fastcrud/advanced/endpoint/#customizing-endpoint-names) either, as it would yield a double slash even if setting the endpoint name for `delete` to an empty string.

**Comment by igorbenav** [comment]
To be honest, I thought passing an empty string was working. Thanks for all the issues, by the way! Really great that you caught all of this stuff. 

About the standard one, I don't have a formed opinion. I think if more people would comment here in favor, maybe we could change it to the cleaner option.

**Comment by JakNowy** [comment]
I had similar thoughts to @waza-ari, I think such simplification would be nice.

**Comment by igorbenav** [comment]
This pagination part has been dealt with in #62, probably not the best option to make unpaginated a default endpoint (people might just add it blindly and then all of a sudden you allow users to get all your data at once). I think we could simplify the standard one though, go for the cleaner version.

Any of you guys want to do it?

**Comment by waza-ari** [comment]
Before saying yes, my question would be how to handle this change. If we change the default endpoint names and go for the "cleaner" version, that has the potential of breaking the code for other users relying on the current default behaviour. What would be your idea around that?

**Comment by igorbenav** [comment]
We add a warning in the release and in the docs and change version from 0.11.x to 0.12.0 to indicate breaking changes. Since we're at 0.y.z, breaking changes are acceptable (we're still figuring things out). We could also add a warning message when using EndpointCreator for the next couple of releases to indicate that things changed.

**Comment by JakNowy** [comment]
@waza-ari would be great if you could help with this!

I would go for GET PATCH and DELETE `/hero/{id}` and POST `/hero/`.
We may leave GET `hero/get_multi/` and GET `/hero/get_paginated/` as it is, while personally, I would love the `get_paginated` to become an optional feature of `/get_multi/` controlled by some query parameters.

We can think about the warnings together once you issue a PR.

**Comment by igorbenav** [comment]
@waza-ari do you still plan to do this?

**Comment by JakNowy** [comment]
@igorbenav  I did some initial investigation on this.

Simplest approach is to override endpoint_names passed to fastcrud.crud_router():

```
endpoint_names = {
    "create": "",
    "read": "",
    "update": "",
    "delete": "",
    "db_delete": "",
    "read_multi": "get_multi",
    "read_paginated": "get_paginated",
}
```

Names for read_multi and read_paginated must be left inplace or they will be registerred twice as the same users/ route (probably read_paginated taking the place as it's the last one registerred). The downside of this is that the route paths are incorrectly containing reduntant slashes:
![image](https://github.com/igorbenav/fastcrud/assets/35011105/ab3b5521-3063-4c17-875b-cd466e3ac697)

This can be further adjusted in EndpointCreator.add_routes_to_router by overriding paths for all views
```
            path = f"{self.path}/{endpoint_name}" if endpoint_name else self.path
        self.router.add_api_route(
            path,
            ...
```

I consider this the simplest approach, however personally I would opt for making the streamlined version the default one (and bumping version to 2 as you mentioned?). I volounteer to work on this if I get your approval.

As I also mentioned, I would like to see `EndpointCreator._read_items` and `EndpointCreator._read_paginated` unified to single read_items where pagination is optionally supported. That will be easy as they all use just read_multi under the hood.

Lastly, I would like to see some easy way to override generic router endpoints.

**Comment by JakNowy** [comment]
cc @waza-ari

**Comment by rmiranda87** [comment]
The streamlined approach would certainly help. To handle the switch, can you just make a parm to switch to streamlined vs original?

**Comment by natehouk** [comment]
This code can lead to an unintended double slash (`//`) when an empty string is passed:

```python
def _get_endpoint_path(self, operation: str):
    endpoint_name = self.endpoint_names.get(
        operation, self.default_endpoint_names.get(operation, operation)
    )
    path = f"{self.path}/{endpoint_name}" if endpoint_name else self.path

    if operation in {"read", "update", "delete", "db_delete"}:
        _primary_keys_path_suffix = "/".join(
            f"{{{n}}}" for n in self.primary_key_names
        )
        path = f"{path}/{_primary_keys_path_suffix}"

    return path
```

1. If `endpoint_name` is an empty string, the variable `path` becomes `self.path/`, ending with a trailing slash.
2. If `operation` is one of `"read"`, `"update"`, `"delete"`, or `"db_delete"`, the code appends `/{_primary_keys_path_suffix}` to `path`.

This sequence of events can result in a double slash (`//`) in the final `path` string.

**Comment by igorbenav** [comment]
This was incorporated in 0.15.0
