### ISSUE TITLE
Is it possible to make is_deleted field redefined and optional?

### ISSUE THREAD

**Issue by lisij86** [igorbenav/fastcrud#88]
https://github.com/igorbenav/fastcrud/blob/adf9ab08c6d7b39b303374a430623846bc6548d3/fastcrud/crud/fast_crud.py#L1697

It would be convenient to make this field redefined to self.is_deleted_column and optional, because in some cases, one deleted_at_column field is enough to understand that the record has been deleted.

**Comment by igorbenav** [comment]
This is possible

**Comment by gsegatti** [comment]
I think we can close this based on #152 being merged?

**Comment by igorbenav** [comment]
Yeah, @gsegatti, I forgot about the closing keywords
